language: cpp

branches:
  only:
    - master

env:
  global:
    - CMAKE_ARGS_ALL="-DBUILD_EXAMPLES=ON -DPostgreSQL_TYPE_INCLUDE_DIR=/usr/share/postgresql/"
  matrix:
    # gcc builds
    - CMAKE_CC="gcc" CMAKE_CXX="g++"         CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"   DB="sqlite"
    - CMAKE_CC="gcc" CMAKE_CXX="g++"         CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release" DB="sqlite"
    # clang builds
    - CMAKE_CC="clang" CMAKE_CXX="clang++"   CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"   DB="sqlite"
    - CMAKE_CC="clang" CMAKE_CXX="clang++"   CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release" DB="sqlite"

    # gcc builds
    - CMAKE_CC="gcc" CMAKE_CXX="g++"         CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"   DB="postgresql"
    - CMAKE_CC="gcc" CMAKE_CXX="g++"         CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release" DB="postgresql"
    # clang builds
    - CMAKE_CC="clang" CMAKE_CXX="clang++"   CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Debug"   DB="postgresql"
    - CMAKE_CC="clang" CMAKE_CXX="clang++"   CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release" DB="postgresql"

install:
  - sudo apt-get -qq update
  - sudo apt-get install libboost-all-dev
  - if [ "$DB" == "postgresql" ]; then sudo apt-get install libpq-dev; fi

before_script:
  - mkdir build && cd build && cmake -DCMAKE_C_COMPILER=$CMAKE_CC -DCMAKE_CXX_COMPILER=$CMAKE_CXX $CMAKE_ARGS $CMAKE_ARGS_ALL -DTEST_DATABASE=$DB  ..
  - if [ "$DB" == "postgresql" ]; then psql -c "CREATE DATABASE $USER;" -U postgres; fi

script:
  - make -j4 && ctest -V
